#!/usr/bin/env zsh
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done

# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

set -ue

remote="$1"
url="$2"

GIT_HOOKS_DIR=$XDG_CONFIG_HOME/git/hooks
. $GIT_HOOKS_DIR/support.zsh

# Remove unnecessary .keep files
if (( $+commands[remove-keep] )); then
  remove-keep -v
fi

# Check if there are duplicated file names with different case
git ls-files | tr '[:upper:]' '[:lower:]' | sort | uniq -d | while read file; do
  echo "Error: Found duplicated file names with different case: $file"
  exit 1
done

set -- $(detect-languages)

while [[ $# -gt 0 ]]; do
  hook=$GIT_HOOKS_DIR/pre-push-$1
  shift
  [[ -x $hook ]] || continue
  echo "Running ${hook:t} hook ..."
  $hook $remote $url || exit 1
done

exit 0
