#!/bin/zsh

function accept-line-with-hooks() {
  run-hooks --until-success accept_line $BUFFER
  if [[ $? = 0 ]]; then
    print -S "$BUFFER"
    BUFFER=""
    zle reset-prompt
  else
    zle accept-line
  fi
}
