#!/bin/zsh

function accept-line-open-uri-hook() {
  case "$BUFFER" in
  http://*|https://*)
    local url="${BUFFER%%\?*}"
    zle quote-line
    case "$url" in
    *.gz|*.bz2|*.tgz|*.zip|*.dmg|*.lzh)
      BUFFER="curl -O $BUFFER"
      ;;
    *)
      BUFFER="open $BUFFER"
      ;;
    esac
    return 0
    ;;
  *)
    return 1
    ;;
  esac
}

typeset -aU accept_line_functions
accept_line_functions+=accept-line-open-uri-hook
