#!/bin/zsh

echo "Collecting ingress information..."
ingress=$(kubectl get ingress --output jsonpath="{.items[*].spec.rules[*].host}" | tr " " "\n" | sed 's,^,https://,' | peco --prompt "Host to connect:")
[[ -n "$ingress" ]] || { bell & return }

BUFFER="open $ingress"
zle accept-line
