#!/bin/zsh

function interactive-chdir()
{
    local input=$1
    local selected=$(eval "$input" | peco --query "$LBUFFER")

    if [[ -n "$selected" ]]; then
        BUFFER="cd $selected"
        zle accept-line
    fi
}
