#!/bin/zsh

upfind -q .git || { bell && return 1 }

local branch=$(git branch | peco --prompt "Branch to checkout:" --query "$LBUFFER" | awk '{print $NF}')
[[ -n "$branch" ]] || { bell & return }

BUFFER="git switch --quiet $branch"
zle accept-line
