#!/bin/zsh

function interactive-chdir() {
    local selected=$(peco --query "$LBUFFER")

    [[ -n "$selected" ]] || return
    [[ -d "$selected" ]] || { echo "$selected is not a directory" && return 1 }
    BUFFER="cd $selected"
    zle accept-line
}
