#!/bin/zsh

function interactive-choose-git-branch() {
  local branch=$(git branch | peco --prompt "Branch to checkout:" --query "$LBUFFER" | awk '{print $NF}')
  if [[ -n "$branch" ]]; then
    BUFFER="git checkout --quiet $branch"
    CURSOR=$#BUFFER
  fi
}
