#!/bin/zsh

function interactive-open-bundled-gem() {
  local dir=$(bundle show | sed --quiet --expression 's/  \* \([^ ][^ ]*\) (.*)$/\1/p' |  peco --query "$LBUFFER" | xargs bundle show)
  if [[ -n "$dir" ]]; then
    BUFFER="$EDITOR $dir"
    zle accept-line
  fi
}
