#!/bin/zsh

function list-tabs()
{
  osascript -l JavaScript <<-'EOF'
  const browser = Application("Google Chrome");
  browser.windows().flatMap((window, i) => window.tabs().map((tab, j) => `${i}:${j}:${tab.title()}`)).join("\n");
EOF
}

function activate-tab()
{
  osascript -l JavaScript - "$@" <<-'EOF'
  function run(argv) {
    const windowIndex = parseInt(argv[0]);
    const tabIndex = parseInt(argv[1]);
    const browser = Application("Google Chrome");
    const window = browser.windows[windowIndex]

    window.activeTabIndex = tabIndex + 1;
    window.index = 1;
    window.visible = true;

    browser.activate();
  }
EOF
}

set -- "${(s|:|)$(list-tabs | peco)}"
[[ -n "$1" && -n "$2" ]] && activate-tab "$1" "$2"
