#!/bin/zsh

upfind -q Rakefile || { bell && return 0 }

echo "Collecting rake tasks..."
local dir
task=$(bundle exec rake --tasks | peco | sed --expression 's/^rake //;s/ *#.*$//')
if [[ -n "$task" ]]; then
  BUFFER="bundle exec rake $task"
  zle accept-line
fi
