#!/bin/zsh

upfind -q Gemfile || { bell && return 0 }
local gem=$(bundle show | sed --expression 1d | peco --query "$LBUFFER" | awk '{print $2}')
[[ -n $gem ]] || { bell && return 0 }
BUFFER="bundle open $gem"
zle accept-line
