#!/bin/zsh

upfind -q .git || { bell && return 1 }

local from=$(git log --pretty=oneline | peco)
local to=$(git log --pretty=oneline | peco)
[[ -n "$from" ]] && [[ -n "$to" ]] || { bell & return }

local repo=$(gh repo view --json owner,name --jq '.owner.login + "/" + .name')

BUFFER="https://github.com/$repo/compare/$from..$to"
zle accept-line
