#!/bin/zsh

upfind -q .git || { bell && return 0 }

local branch=$(git branch | peco --prompt "Branch to checkout:" --query "$LBUFFER" | awk '{print $NF}')
if [[ -n "$branch" ]]; then
  BUFFER="git checkout --quiet $branch"
  CURSOR=$#BUFFER
fi
