#!/bin/zsh

function peco-git-choose-branch() {
  local branch=$(git branch | peco --prompt "Branch to checkout:" --query "$BUFFER" | awk '{print $NF}')
  if [[ -n "$branch" ]]; then
    BUFFER="git checkout -q $branch"
    CURSOR=$#BUFFER
  fi
}
