#!/bin/zsh

exec > >(sed -ue 's/^/[pre-install] /')

echo "Installing ruby $1"

export RUBY_CONFIGURE_OPTS='--enable-shared
  --disable-install-doc
  --with-opt-dir=/opt/local
  --with-readline-dir=/opt/local
  --with-libyaml-dir=/opt/local
  --with-openssl-dir=/opt/local'

echo "Configure options: $RUBY_CONFIGURE_OPTS"
