#!/bin/zsh

exec > >(sed -ue 's/^/[pre-install] /')

echo "Installing ruby $1"

export RUBY_CONFIGURE_OPTS="--enable-shared
  --disable-install-doc
  --with-readline-dir=$(brew --prefix readline)
  --with-libyaml-dir=$(brew --prefix libyaml)
  --with-openssl-dir=$(brew --prefix openssl@1.1)"

echo "Configure options: $RUBY_CONFIGURE_OPTS"
