memcached:
  container_name: memcached
  image: memcached:1.4.36-alpine
  ports:
    - "11211:11211"

postgresql:
  container_name: postgresql
  image: postgres:9.5-alpine
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: "${USER}"
    POSTGRES_INITDB_ARGS: "--encoding UTF8 --no-locale"
