#!/bin/zsh

[[ $1 = https://github.com/*/*.git ]] || return 1

local url=$1
local repo=${${url%.git}#*://*/}
local dir=$HOME/github.com/$repo

echo ""

if [[ -d $dir ]]; then
  echo $repo exists
else
  (unset PS4; set -x; gh repo clone $url $dir)
fi
REPLY=$?
