#!/bin/zsh

[[ $1 = (http://*|https://*) ]] || return 1

local url="${1%%\?*}"

[[ $url = (*.gz|*.bz2|*.tgz|*.zip|*.dmg|*.lzh) ]] || return 1

echo ""
(unset PS4; set -x; curl --remote-name $url)
REPLY=$?
