#!/bin/zsh

[[ $1 = https://github.com/*/*.git ]] || return 1

local url=$1
local repo=${${url%.git}#*://*/}
local owner=$repo:h
local owner_dir=$HOME/github.com/$owner
echo ""
(mkdir -p $owner_dir && cd $owner_dir && {
  if [[ -d $repo:t ]]; then
    echo $repo exists
  else
    gh repo clone $url
  fi
})
REPLY=$?
