deploy:
	scripts/deploy.sh

brew:
	scripts/homebrew.sh

bundle-dump:
	brew bundle dump --force

vscode-extensions:
	scripts/vscode.sh

asdf-update-tool-versions:
	scripts/asdf-update-tool-versions.sh
