#!/bin/zsh

source ~/.tmux.d/widgets/tmux-bar

AIRPORT_FRAMEWORK=/System/Library/PrivateFrameworks/Apple80211.framework
AIRPORT_COMMAND=$AIRPORT_FRAMEWORK/Versions/Current/Resources/airport

set -- ${${(@f)"$($AIRPORT_COMMAND -I| egrep "agrCtlRSSI|state|lastTxRate| SSID")"}#*:}

tmux-bar ${1:--100} -94:-92:-86:-79

