#!/bin/zsh

source ~/.tmux.d/widgets/tmux-bar

set -- ${${(@f)"$(pmset -g ps|LC_ALL=C egrep --ignore-case -o '\w+ Power|[0-9]+%')"}}

ac_icon="🔌"
battery_icon="🔋"

case $1 in
Battery*) icon="$battery_icon" ;;
AC*) icon="$ac_icon" ;;
esac

echo "${icon}$(tmux-bar ${2%%\%} 20:40:60:80)"
