#!/bin/zsh

PATH=$ZPLUG_BIN:/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources:$PATH

local rssi
local state
local ssid

airport --getinfo | while read line; do
  local words=(${(ps.: .)line})
  case $words[1] in
  agrCtlRSSI) rssi=$words[2] ;;
  state)      state=$words[2] ;;
  SSID)       ssid=$words[2] ;;
  esac
done

case $state in
running) echo "#[fg=brightcyan]:wifi:  $ssid#[fg=default]" | fontawe ;;
init)    echo "#[fg=gray]:wifi:  :ellipsis-h:#[fg=default]" | fontawe ;;
*)       echo "#[fg=red]:wifi:  :ban:#[fg=default]" | fontawe ;;
esac
