#!/bin/zsh

PATH=$HOME/.tmux.d/widgets:$PATH

tmux_current_path="$(tmux display -p '#{pane_current_path}')"
cd $tmux_current_path && echo " #P: [$(tmux-vcs-info):$(tmux-pwd)] [$(tmux-rbenv-version)] "
