#!/bin/zsh

PATH=

if [[ -r /proc/loadavg ]]; then
  set -A la $(< /proc/loadavg)
elif is-executable /usr/sbin/sysctl; then
  set -A la $(/usr/sbin/sysctl -n vm.loadavg)
  la=$la[2,-2]
else
  return 0
fi

case $la[1] in
*0.*)
  echo "#[fg=gray]:chart-area:  ${la}#[fg=default]" ;;
*1.*)
  echo "#[fg=yellow]:chart-area:  ${la}#[fg=default]" ;;
*2.*)
  echo "#[fg=magenta]:chart-area:  ${la}#[fg=default]" ;;
*)
  echo "#[fg=red]:chart-area:  ${la}#[fg=default]" ;;
esac
