#!/bin/zsh

source ~/.tmux.d/widgets/tmux-bar

set -- ${${(@f)"$(pmset -g ps|LC_ALL=C egrep --ignore-case -o '\w+ Power|[0-9]+%')"}}

ac_icon="🔌"
battery_icon="🔋"

icon="$battery_icon"
echo "${icon}$(tmux-bar ${2%%\%} 20:40:60:80)"
