#!/bin/zsh

fullscreen=false

while [[ $# -gt 0 ]]; do

  case $1 in
  fullscreen) fullscreen=true ;;
  esac

  shift
done

if $fullscreen; then
  tmux set -g status-left-length 10 > /dev/null 2>&1
else
  tmux set -g status-left-length 0 > /dev/null 2>&1
fi

exit 0
