#!/bin/zsh

# Brightness = max(Red, Green, Blue)

function get_terminal_setting()
{
  osascript -e "tell application \"Terminal\" to get $1 of window 1"
}

function get_iterm_setting()
{
  osascript -e "tell application \"iTerm\" to get $1 of current session of terminal 1"
}

function get_foreground_color()
{
  case "$TERM_PROGRAM" in
  iTerm.app)
    get_iterm_setting 'foreground color' ;;
  Apple_Terminal)
    get_terminal_setting 'normal text color' ;;
  *)
    ;;
  esac
}

function get_background_color()
{
  case "$TERM_PROGRAM" in
  iTerm.app)
    get_iterm_setting 'background color' ;;
  Apple_Terminal)
    get_terminal_setting 'background color' ;;
  *)
    ;;
  esac
}

set -- ${(On)$(get_foreground_color)%,} ${(On)$(get_background_color)%,}

if [[ $1 -gt $4 ]]; then
  echo dark
else
  echo light
fi
