#!/bin/zsh

unalias -m '*'
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias history='history -i 1'
alias du='du -h'
alias df='df -h'
is_executable free && alias free='free -t -m'
is_executable vim && alias vi='vim'
alias -g V='| view -'
alias -g L='| lv'
is_executable mysql5 && alias mysql=mysql5
alias puts='print -l'
alias wget='curl -O'

alias rg='script/rails generate'
alias rc='script/rails console'
alias rs='script/rails sever'
alias rc='script/rails dbconsole'
