#!/bin/zsh

if whence -p lv > /dev/null; then
  PAGER=lv
  export LV=-dc
elif whence -p less > /dev/null; then
  PAGER=less
  export LESS=-im
else
  PAGER=more
fi

export PAGER
export READNULLCMD=$PAGER
