#!/bin/zsh

# color ls
is_executable dircolors && [[ -f ~/.dircolors ]] && {
  eval $(dircolors -b ~/.dircolors)
  alias ls='ls -F --color'
}

autoload -U colors
colors

# color grep
GREP_COLOR=$color[cyan]
export GREP_COLOR
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
