#!/bin/zsh

DEFAULT_PACKAGES=$XDG_CONFIG_HOME/asdf/hooks/nodejs/default-packages

exec > >(sed --unbuffered --expression "s/^/[nodejs-$1][post-install] /")

echo "Switching to newly installed Node.js $1"
source $ASDF_DIR/asdf.sh
asdf shell nodejs $1
echo "Node.js version: $(node --version)"
echo "npm version: $(npm --version)"

echo "Installing default packages for nodejs $1"
while read package; do
  echo "Installing $package"
  npm install --global "$package"
done < $DEFAULT_PACKAGES

echo "Done"
