#!/bin/zsh -e
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done

# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

remote="$1"
url="$2"

GIT_HOOKS_DIR=$XDG_CONFIG_HOME/git/hooks
. $GIT_HOOKS_DIR/support.zsh

languages=$(detect-languages)

while [[ $#languages -gt 0 ]]; do
  hook=$GIT_HOOKS_DIR/pre-push-$1
  [[ -x $hook ]] && $hook $remote $url || exit 1
done

exit 0
