#!/bin/zsh

function accept-line-with-hooks() {
  local hook
  if [[ $#accept_line_functions -gt 0 && -n "$BUFFER" ]]; then
    for hook in $accept_line_functions; do
      zle $hook && break
    done
  fi
  zle accept-line
}

typeset -aU accept_line_functions
