#!/bin/zsh

function peco-chdir-bundle-show()
{
  local dir=$(bundle show | sed -n 's/  \* \([^ ][^ ]*\) (.*)$/\1/p' |  peco --query "$LBUFFER" | xargs bundle show)
  if [[ -n "$dir" ]]; then
    BUFFER="cd $dir"
    zle accept-line
  fi
}
