#!/bin/zsh

missing="$1"
shift

exe="${missing}.exe"
com="${missing}.com"
app_bundled="/Applications/${missing}.app/Contents/MacOS/$missing"

if (( $+commands[${exe}] )); then
  # try invoking .exe version
  exec "${exe}" "$@"
elif (( $+commands[${com}] )); then
  # try invoking .com version
  exec "${com}" "$@"
elif (( $+commands[${app_bundled}] )); then
  exec "${app_bundled}" "$@"
else
  # emulate original zsh behavior
  echo "$SHELL:t: command not found: ${missing}" >&2
  exit 127
fi
