#!/bin/zsh

[[ $# = 2 ]] || usage "hook-name hook-function" || return 1

local hook="${1}_functions"
local f=$2

if [[ ${(P)+hook} = 1 ]]; then
  set -A $hook ${(P)hook} $f
else
  typeset -agU $hook
  set -A $hook $f
fi
