#!/bin/zsh

zsh_hooks=(chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name)

[[ $# = 2 ]] || usage "hook-name hook-function" || return 1

is-member-of "$1" "${zsh_hooks[@]}" && {
  usage "hook-name hook-function" "Use add-zsh-hook for $1"
  return 1
}

local hook="${1}_functions"
local f=$2

if [[ ${(P)+hook} = 1 ]]; then
  set -A $hook ${(P)hook} $f
else
  typeset -agU $hook
  set -A $hook $f
fi
