#!/bin/zsh

if [[ $# -lt 2 ]]; then
  echo "asdf-each PLUGIN_NAME COMMAND"
  return 1
fi
local plugin_name="$1"
shift
if [[ $1 = -* ]]; then
  set -- $plugin_name "$@"
fi

local versions=( $(asdf list "$plugin_name") )
for version in $versions; do
  (asdf shell "$plugin_name" $version; "$@")
done
