#!/fin/zsh

DOTDIR=$HOME/.dotfiles

case $# in
0)
  [[ -d $DOTDIR ]] && cd $DOTDIR && return 0 ;;
1)
  case $1 in
  edit)
    ${(z)EDITOR} $DOTDIR && return 0 ;;
  esac
esac

usage <<USAGE
$0 - chdir to dotfiles directory
$0 edit - open dotfiles directory in editor
USAGE

return 1
