#!/fin/zsh

DOTDIR=$HOME/.dotfiles

function error_usage()
{
  echo "dotfiles [edit | update | dump]"
}

case $# in
0)
  [[ -d $DOTDIR ]] && cd $DOTDIR
  ;;
1)
  case $1 in
    edit)
      ${(z)EDITOR} $DOTDIR ;;
    update)
      make up-to-date -C $DOTDIR ;;
    dump)
      make dump-brewfile -C $DOTDIR ;;
    *)
      error_usage ;;
  esac
  ;;
*)
  error_usage ;;
esac
