#!/fin/zsh

DOTDIR=$HOME/.dotfiles

case $# in
0)
  [[ -d $DOTDIR ]] && cd $DOTDIR && return 0 ;;
1)
  case $1 in
  edit)
    ${(z)EDITOR} $DOTDIR && return 0 ;;
  esac
esac

usage "[edit]"

return 1
