#!/bin/zsh

set -eu

function clean_root()
{
  [[ -d "$root" ]] && rm -rf "$root"
}

root=$1
shift

if [[ -d "$root" ]]; then
  echo Directory $root already exists.
  exit 1
fi

mkdir "$root"
trap clean_root INT TERM

pushd $root

# Create the app
cat <<GEMFILE > Gemfile
source 'https://rubygems.org'
gem 'hanami', '~> 1.3.0.beta1'
gem 'hanami-model', '~> 1.3.0.beta1'
GEMFILE

bundle config --local path vendor/bundle >/dev/null
bundle install
bundle exec hanami new . $*
bundle install
bundle clean

cat <<GITIGNORE >> .gitignore
/.bundle
/vendor/bundle
GITIGNORE

# Add binstubs
cat <<RUBY | bundle exec ruby | xargs bundle binstub
puts Gem::Specification.select{|s|s.executables.any?}.map(&:name)
RUBY

# Initial commit
git add .
commit_message=$(mktemp -t hanami-new.commit.XXXXXXXX)
cat <<COMMIT_MESSAGE > $commit_message
Initial commit

$ hanami new $root $*
COMMIT_MESSAGE

git commit --file $commit_message

if is-executable direnv; then
  touch .envrc
  direnv allow .
fi

popd

# End
