#!/bin/zsh

is-executable tmux || return
tty --silent || return
[[ "$TERM_PROGRAM" = vscode && -t 1 ]] && return
in-jediterm && return
[[ -n "$TMUX" ]] && return

local sessions=( ${(f)"$(tmux list-sessions 2>/dev/null)"} )
if [[ $#sessions -eq 0 ]]; then
  tmux new-session
else
  local session=$(echo "${(F)sessions}\nN:ew session" | peco --prompt "Session to attach:" | cut --delimiter=: --fields=1)
  case $session in
  N) tmux new-session ;;
  *) tmux attach-session -t $session ;;
  esac
fi
