#!/bin/zsh

(
  netstat -lanp tcp | sed '1,2d' | awk '{print $4}' | awk --field-separator . 'NF == 5 {print $5}' | sort --numeric-sort | uniq
  seq 1 60000
  seq 1 65535
) | sort --numeric-sort | uniq --unique | shuf --head-count 1
