#!/bin/zsh

funcdtion xdg() {
  local create=false
  if [[ $1 = "-c" ]]; then
    create=true
    shift
  fi

  case $1 in
  config) dir=$HOME/.config ;;
  cache) dir=$HOME/.cache ;;
  data) dir=$HOME/.local/share ;;
  *) echo "Usage: $0 [-c] {config|cache|data}" ; return 1 ;;
  esac

  [[ -d "${dir}" ]] || $create && mkdir -p "${dir}"
  echo "${dir}"
}

alias xdg-home=xdg
