#!/bin/zsh

function bundler_alias()
{
  export LAST_GEMFILE
  local gemfile=$(upfind Gemfile)

  if [[ -z "$gemfile" || "$gemfile" != "LAST_GEMFILE" ]]; then
    local alias_name
    for alias_name in ${(k)aliases}; do
      [[ $aliases[$alias_name] == "bundle exec $alias_name" ]] && unalias $alias_name
    done
  fi

  if [[ "$gemfile" != "$LAST_GEMFILE" && $gemfile.lock -nt $gemfile ]]; then
    local bin
    for bin in ${(@f)"$(ruby -rbundler/setup -e 'Bundler.setup; puts Gem::Specification.map(&:executables).flatten.uniq')"}; do
      [[ $bin = bundle ]] || alias $bin='bundle exec '$bin
    done
  fi

  LAST_GEMFILE=$gemfile
}
