#!/bin/zsh

function colorize()
{
  local added="$(tput setaf 2)"    # green
  local deleted="$(tput setaf 1)"  # red
  local modified="$(tput setaf 6)" # cyan
  local unknown="$(tput setaf 3)"  # yellow
  local heading="$(tput setaf 3)"  # yellow
  local reset="$(tput sgr0)"       # reset

  sed \
      -e "s/^A[M ][L ][+ ][S ] .*/$added&$reset/;" \
      -e "s/^D[M ][L ][+ ][S ] .*/$deleted&$reset/;" \
      -e "s/^M[M ][L ][+ ][S ] .*/$modified&$reset/;" \
      -e "s/^.M[L ][+ ][S ] .*/$modified&$reset/;" \
      -e "s/^?.*/$unknown&$reset/;" \
      -e "s/^+++ .*/$added&$reset/;" \
      -e "s/^+.*/$added&$reset/;" \
      -e "s/^+$/$added&$reset/;" \
      -e "s/^--- .*/$deleted&$reset/;" \
      -e "s/^-.*/$deleted&$reset/;" \
      -e "s/^-$/$deleted&$reset/;" \
      -e "s/^@@ .*/$modified&$reset/;" \
      -e "s/^Index: .*/$heading&$reset/;" \
      -e "s/^==*$/$heading&$reset/;" \
      -e "/^r[0-9][0-9]* .* [0-9][0-9]* lines*\$/s/.*/$heading&$reset/"
}
