#!/bin/zsh

function load_avg()
{
  if [[ -r /proc/loadavg ]]; then
    set -- $(< /proc/loadavg)
  elif [[ -x /usr/sbin/sysctl ]]; then
    set -- $(/usr/sbin/sysctl -n vm.loadavg)
    shift
  else
    return 0
  fi
  case $1 in
  0.*)
    echo '%F{gray}'
    ;;
  1.*)
    echo '%B%F{yellow}'
    ;;
  2.*)
    echo '%BF{magenta}'
    ;;
  3.*)
    echo '%F{red}'
    ;;
  esac
}
