#!/bin/zsh

function rc()
{
  local ruby="$(rbenv which ruby)"
  local command="$ruby script/rails console"
  if in_screen; then
    screen -t "$PWD:t console" ${=command} $*
  else
    ${=command} $*
  fi
}

