#!/bin/zsh

function rdb()
{
  local ruby="$(rbenv which ruby)"
  local command="$ruby script/rails dbconsole"
  if in_screen; then
    screen -t "$PWD:t db" ${=command} $*
  else
    ${=command} $*
  fi
}

