#!/bin/zsh

local alias
for alias in $(alias | sed -n '/bundle exec/s/=.*//p'); do
  unalias "$alias"
done

local gemfile=$(upfind Gemfile)

[[ $? = 0 ]] || return 0
[[ -f "$gemfile.lock" ]] || return 0
if [[ "$gemfile.lock" -ot $gemfile ]]; then
  echo "WARNING: Gemfile.lock needs update"
fi
for bin in $(ruby -rbundler -e 'Bundler.setup' -e 'puts Gem::Specification.flat_map(&:executables)'); do
  [[ $bin = bundle ]] || alias $bin='bundle exec '$bin
done
