#!/bin/zsh

[[ -f ${path[1]:h}/Gemfile ]] && shift path

local gemfile=$(upfind Gemfile)
[[ -n $gemfile ]] || return 0

local binstub_dir=${gemfile:h}/bin
[[ -d $binstub_dir ]] || return 0

path=( $binstub_dir $path )
