#!/bin/zsh

function update-bundler-aliases()
{
  if [[ -f Gemfile.lock ]]; then
    if [[ Gemfile.lock -ot Gemfile ]]; then
      echo "WARNING: Gemfile.lock needs update"
    fi
    for bin in $(ruby -rbundler/setup -e 'Bundler.setup' -e 'puts Dir["#{Bundler.bundle_path}/bin/*"].map{|f| File.basename(f)}'); do
      [[ $bin = bundle ]] || alias $bin='bundle exec '$bin
    done
  else
    for alias in $(alias | sed -n -e "s/='bundle exec .*'//p"); do
      unalias "$alias"
    done
  fi
}

