#!/bin/zsh

DEFAULT_GEMS=$XDG_CONFIG_HOME/asdf/hooks/ruby/default-gems

exec > >(sed --unbuffered --expression "s/^/[ruby-$1][post-install] /")

echo "Switching to newly installed ruby $1"
source $ASDF_DIR/asdf.sh
asdf shell ruby $1
echo "Ruby version: $(ruby -v)"

if gem list | grep --quiet bundler; then
  echo "Updating bundler for ruby $1"
  gem update bundler --no-post-install-message --no-document
else
  echo "Installing bundler for ruby $1"
  gem install bundler --no-post-install-message --no-document
fi
bundle version

echo "Updating rubygems for ruby $1"
gem update --system --no-post-install-message --no-document
gem uninstall rubygems-update --all --executables
echo "Rubygems version: $(gem -v)"

echo "Installing default gems for ruby $1"
while read gem; do
  echo "Installing $gem"
  gem install $gem --no-post-install-message --no-document
done < $DEFAULT_GEMS

echo "Done"
