#!/bin/zsh

exec > >(sed --unbuffered --expression "s/^/[ruby-$1][pre-install] /")

echo "Installing ruby $1"

export RUBY_CONFIGURE_OPTS="--enable-shared --disable-install-doc "
CFLAGS="-O0 -ggdb3"

case $1 in
2.6.7)
  export CFLAGS="${CFLAGS} -Wno-error=implicit-function-declaration"
  ;;
esac


case "${OSTYPE}" in
darwin*)
  if brew --version >/dev/null 2>/dev/null; then
    export RUBY_CONFIGURE_OPTS="$RUBY_CONFIGURE_OPTS
      --with-readline-dir=$(brew --prefix readline)
      --with-libyaml-dir=$(brew --prefix libyaml)
      --with-openssl-dir=$(brew --prefix openssl@1.1)"
  fi
  ;;
esac

echo "Configure options: $RUBY_CONFIGURE_OPTS"
echo "CFLAGS: $CFLAGS"
