#!/bin/zsh

PATH="$XDG_CONFIG_HOME/tmux/widgets:$PATH"

airport_cmd=/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport

if [[ -x $airport_cmd ]]; then
  local info=(${(f)"$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep -oP '(?<=agrCtlRSSI: -)(\d+)|(?<=SSID: )(?<!BSSID: )(.*)')"})
  strength=$((100 - $info[1]))
  ssid=$info[2]
fi

if [[ -n $strength ]]; then
  level=$((strength / 12.5))
  print -nP "\U1F4F6"
  tmux-levels cyan white $level
  print -nP "$ssid"
fi
