#!/bin/zsh

autoload is-executable
autoload upfind

is-executable git && upfind -q .git && {
  local vcs_symbol="\ue725"

  local branch="#[fg=blue]$(git symbolic-ref --short HEAD)#[default]"

  local git_status=$(git status --porcelain=v1 --branch)
  [[ "$git_status" = *"ahead"* ]]
  local ahead=$(print -P '%(?,#[fg=green]↑#[default],)')
  [[ "$git_status" = *"behind"* ]]
  local behind=$(print -P '%(?,#[fg=red]↓#[default],)')
  [[ "$git_status" = *'??'* ]]
  local untracked=$(print -P '%(?,#[fg=yellow]?#[default],)')
  print -P "$vcs_symbol $branch$untracked$behind$ahead"
}
