#!/bin/zsh

PATH="$XDG_CONFIG_HOME/tmux/widgets:$PATH"

if [[ -r /proc/loadavg ]]; then
  set -- $(< /proc/loadavg)
  ncpu=$(< /proc/cpuinfo | grep '^processor' |wc -l)
elif [[ -x /usr/sbin/sysctl ]]; then
  set -- $(/usr/sbin/sysctl -n vm.loadavg)
  shift
  ncpu=$(/usr/sbin/sysctl -n hw.ncpu)
else
  return
fi

local load_average=$(( $1 / $ncpu ))
local -i load_average_scaled=$(( $load_average * 4 ))
print -nP "\U1F4C8"
case $load_average_scaled in
0|1|2|3|4) tmux-levels magenta white $load_average_scaled ;;
*) tmux-levels red white $load_average_scaled ;;
esac
