#!/bin/zsh

autoload is-executable

local ruby_symbol="\ue23e"
local ruby_version_array=( $(asdf current ruby) )
local ruby_version=$ruby_version_array[2]
[[ $? == 0 ]] && print -nP "#[fg=red]${ruby_symbol} ${ruby_version}#[default]"
