#!/bin/zsh

PATH="$XDG_CONFIG_HOME/tmux/widgets:$PATH"

if is-executable osascript; then
  set -- $(osascript -e 'get volume settings' | grep -oP '(?<=output volume:)\d+|(?<=output muted:)(true|false)')
  local -i volume=$1
  muted=$2
fi

if $muted; then
  print -nP "\U1F507" # SPEAKER WITH CANCELLATION STROKE
elif [[ -n $volume ]]; then
  integer level=$((volume / 12.5))
  print -nP "\U1F50A" # SPEAKER WITH THREE SOUND WAVES
  tmux-levels yellow white $level
fi
