#!/bin/zsh

PATH="$XDG_CONFIG_HOME/tmux/widgets:$PATH"

if is-executable osascript; then
  set -- $(osascript -e 'get volume settings' | grep -oP '(?<=output volume:)\d+|(?<=output muted:)(true|false)')
  local -i volume=$1
  muted=$2
fi

if $muted; then
  print -nP "\U1F507" # SPEAKER WITH CANCELLATION STROKE
elif [[ -n $volume ]]; then
  integer level=$((volume / 12.5))
  integer waves=$((volume / 50 + 1))
  case $waves in
  1) print -nP "\U1F509" ;; # SPEAKER WITH ONE SOUND WAVE
  *) print -nP "\U1F50A" ;; # SPEAKER WITH THREE SOUND WAVES
  esac
  tmux-levels yellow white $level
fi
