#!/bin/zsh

PATH="$XDG_CONFIG_HOME/tmux/widgets:$PATH"

is-executable pmset || return

set -- $(pmset -g ps | grep --only-matching --perl-regexp '(?<=Now drawing from '\'')(AC|Battery)|(\d+)(?=%;)|(charged|charging|dischargin)')
source=$1
percentage=$2
state=$3

if [[ -n $percentage ]]; then
  integer level=$(( percentage / 12.5 ))
  tmux-levels green white $level
  print -n "$percentage%"
fi

case $state in
charging)
  print -nP "\U26A1" ;;
esac

case $source in
AC)
  print -P "\U1F50C" ;;
Battery)
  print -P "\U1F50B" ;;
esac
