#!/bin/zsh

autoload vcs_info
zstyle ':vcs_info:*'     formats       '%F{blue}%b%f' '%S'
zstyle ':vcs_info:*'     actionformats '%b%F{cyan}:%F{red}%a%f'
zstyle ':vcs_info:svn:*' branchformat  '%F{blue}%b%F{cyan}:%fr%r'
zstyle ':vcs_info:*' enable git svn hg bzr cvs

local pwd_symbol="\uf115"
local result
local vcs_info_msg_0_ vcs_info_msg_1_
LANG=C vcs_info
local base_path="$(print -P '%~')"

# remove repository_part($vcs_info_msg_1_)
[[ -n "$vcs_info_msg_0_" && $vcs_info_msg_1_ != '.' ]] && base_path="${base_path%/$vcs_info_msg_1_}"
typeset -la path_elements
set -A path_elements ${(s:/:)base_path}

if [[ $#path_elements -gt 2 ]]; then
  local first="$path_elements[1]"
  [[ "$first" = '~'* ]] || first="/$first"
  local last="$path_elements[-1]"
  base_path="$first/"${(j:/:)$(print -P '%2>.>'${^${(@)path_elements[2,-2]}})}/"$last"
fi

result="#[fg=magenta]${pwd_symbol} ${base_path}#[default]"
[[ -n "$vcs_info_msg_1_" && "$vcs_info_msg_1_" != '.' ]] && result+="/#[fg=cyan]$vcs_info_msg_1_#[default]"

print -n "${result}"
