#!/bin/zsh

PATH="$XDG_CONFIG_HOME/tmux/widgets:$PATH"

airport_cmd=/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport

[[ -x $airport_cmd ]] || return

local info=(${(f)"$($airport_cmd -I | grep --only-matching --perl-regexp '(?<=agrCtlRSSI: -)(\d+)|(?<=SSID: )(?<!BSSID: )(.*)')"})
strength=$((100 - $info[1]))
ssid=$info[2]

if [[ -n $strength ]]; then
  level=$((strength / 12.5))
  tmux-levels cyan white $level
  print -nP "\U1F4F6"
  print -nP "$ssid"
fi
