#!/bin/zsh

script_name="$0:t"

(( $+commands[emojify] )) && exec > >(sed "s/^/[${script_name}] /" | emojify)

# Link this script from .git/hooks
echo ":computer: Running ${script_name} hook..."
echo ":link: Updating symlinks"
mise run link-dotfiles

if (( $+commands[mise] )); then
  echo ":wrench: Updating tools"
  mise install
  mise prune --yes
fi
