run 'yamadera apply finalize'
run 'yamadera apply direnv'
run 'yamadera apply pry'
run 'yamadera apply rspec'
run 'yamadera apply rubocop'
run 'yamadera apply yard'
run 'yamadera apply slim'
run 'yamadera apply quiet_assets'
