#!/bin/zsh

source "${0:h}/support.zsh"

function need-bundle-update() {
  [[ -f Gemfile ]] && git ls-files --error-unmatch Gemfile.lock >/dev/null 2>/dev/null && [[ Gemfile.lock -ot Gemfile ]]
}

if need-bundle-update; then
  echo "Gemfile.lock is not up to date.  Run bundle install"
  return 1
fi

for command in rubocop rspec yard; do
  command-in-path $command || continue
  echo "Running $command"
  command $command || return 1
done
