[bootstrap.packages]
"brew:coreutils" = "latest"
"brew:diffutils" = "latest"
"brew:findutils" = "latest"
"brew:gawk" = "latest"
"brew:git" = "latest"
"brew:gnu-sed" = "latest"
"brew:grep" = "latest"
"brew:inetutils" = "latest"
"brew:libyaml" = "latest"
"brew:neovim" = "latest"
"brew:netpbm" = "latest"
"brew:pkgconf" = "latest"
"brew:pstree" = "latest"
"brew:rsync" = "latest"
"brew:watch" = "latest"
"brew:zsh-autosuggestions" = "latest"
"brew:zsh-completions" = "latest"
"brew:zsh-syntax-highlighting" = "latest"
"brew-cask:1password" = "latest"
"brew-cask:1password-cli" = "latest"
"brew-cask:claude-code" = "latest"
"brew-cask:font-cica" = "latest"
"brew-cask:font-ricty-diminished" = "latest"
"brew-cask:google-chrome" = "latest"
"brew-cask:hammerspoon" = "latest"
"brew-cask:keyboard-cleaner" = "latest"
"brew-cask:keycastr" = "latest"
"brew-cask:visual-studio-code" = "latest"
"brew-cask:wezterm" = "latest"

[bootstrap.macos.launchd.agents.ipconfig-verbose]
program = "/usr/bin/sudo"
args = ["/usr/sbin/ipconfig", "setverbose", "1"]
run_at_load = true

[bootstrap.files."/etc/sudoers.d/nopasswd"]
source = "./files/sudoers.macos"
owner = "root"
group = "wheel"
mode = "0444"

[tasks.link-git-credential-config]
run = "ln -fsv {{ xdg_config_home }}/git/include/credential.darwin {{ xdg_config_home }}/git/include/credential"

[tasks.post-setup]
depends = ["link-git-credential-config"]
