[tools]
deno = "2.2.1"
node = "23.11.0"
ruby = "3.4.3"

[settings]
experimental = true

[settings.ruby]
verbose_install = true
default_packages_file = "~/.config/mise/default-gems"
ruby_build_opts = "--disable-install-doc"
