[bootstrap.packages]
"apt:dnsutils" = "latest"
"apt:git" = "latest"
"apt:less" = "latest"
"apt:locales" = "latest"
"apt:neovim" = "latest"
"apt:postgresql-client" = "latest"
"apt:rsync" = "latest"
"apt:sqlite3" = "latest"
"apt:sudo" = "latest"
"apt:unzip" = "latest"
"apt:xdg-utils" = "latest"
"apt:zsh" = "latest"
"apt:zsh-autosuggestions" = "latest"
"apt:zsh-syntax-highlighting" = "latest"

[bootstrap.files."/etc/sudoers.d/nopasswd"]
source = "./files/sudoers.nopasswd.linux"
owner = "root"
group = "root"
mode = "0444"

[tasks.os-specific-bootstrap]
depends = ["configure-locales", "link-git-credential-config"]

[tasks.configure-locales]
run = "sudo sed -i '/ja_JP.UTF-8/s/^# *//' /etc/locale.gen && sudo /usr/sbin/locale-gen --keep-existing"

[tasks.link-git-credential-config]
shell = 'bash'
run = '''
    if [[ -n "$WSL_DISTRO_NAME" ]]; then
      if [[ -x "/mnt/c/Program Files/Git/mingw64/libexec/git-core/git-credential-manager.exe" ]]; then
        ln -fsv "{{ xdg_config_home }}/git/include/credential.windows" "{{ xdg_config_home }}/git/include/credential"
      fi
    fi
'''
