[tools]
actionlint = "latest"
aws-cli = "latest"
aws-vault = "latest"
bat = "latest"
difftastic = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
jq = "latest"
kubectl = "latest"
node = "latest"
op = "latest"
ripgrep = "latest"
ruby = "4.0"
rust = "latest"
terraform = "latest"
tflint = "latest"
uv = "latest"
yq = "latest"
"aqua:awslabs/git-secrets" = "1.3.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
verbose_install = true
default_packages_file = "~/.config/mise/default-gems"
ruby_build_opts = "--disable-install-doc"

[env]
MISE_NODE_DEFAULT_PACKAGES_FILE = "{{ [config_root] | concat(with='.config/mise/default-npm-packages') | join_path }}"


