# [bootstrap.packages] section is separated in os specific config files.

[bootstrap.repos]
"~/.dotfiles" = { url = "https://github.com/sakuro/dotfiles.git" }

[bootstrap.user]
login_shell = "/bin/zsh"

[dotfiles]
"~/bin" = { mode = "symlink-each" }
"~/.config" = { mode = "symlink-each" }
"~/.claude" = { source = "~/.config/claude" }
"~/.zshenv" = { }
"~/.dotfiles/.git/hooks/post-merge" = { source = "~/.dotfiles/scripts/post-merge" }

[tasks.bootstrap]
depends_post = ["os-specific-bootstrap"]

[tools]
bat = "0.26.1"
difftastic = "0.70.0"
fzf = "0.74.3"
gh = "2.97.0"
jq = "1.8.2"
op = "2.34.1"
ripgrep = "15.2.0"
ruby = "4.0"
#"gem:fasti" = "latest"
"github:damienbutt/emojify-go" = "latest"
"github:sakuro/factorix" = "0.22.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
minimum_release_age = "3d"

[settings.node]
default_packages_file = "~/.config/mise/files/default-npm-packages"

[settings.ruby]
verbose_install = true
default_packages_file = "~/.config/mise/files/default-gems"
ruby_build_opts = "--disable-install-doc"
