[tools]
deno = "2.1.4"
node = "23.5.0"
ruby = "3.4.1"

[settings]
experimental = true

[settings.ruby]
verbose_install = true
default_packages_file = "~/.config/mise/default-gems"
ruby_build_opts = "--disable-install-doc"
