[tools]
deno = "2.5"
node = "24.9"
ruby = "3.4"
rust = "1.90"

sops = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
verbose_install = true
default_packages_file = "~/.config/mise/default-gems"
ruby_build_opts = "--disable-install-doc"

[env]
MISE_NODE_DEFAULT_PACKAGES_FILE = "{{ [config_root] | concat(with='.config/mise/default-npm-packages') | join_path }}"


