[tools]
deno = "1.46.3"
node = "22.9.0"
ruby = "3.3.5"

[settings]
experimental = true

[settings.ruby]
verbose_install = true
default_packages_file = "~/.config/mise/default-gems"
ruby_build_opts = "--disable-install-doc"
