[bootstrap.packages]
"apt:dnsutils" = "latest"
"apt:less" = "latest"
"apt:neovim" = "latest"
"apt:postgresql-client" = "latest"
"apt:rsync" = "latest"
"apt:sqlite3" = "latest"
"apt:unzip" = "latest"
"apt:xdg-utils" = "latest"
"apt:zsh" = "latest"
"apt:zsh-autosuggestions" = "latest"
"apt:zsh-syntax-highlighting" = "latest"

[bootstrap.files."/etc/sudoers.d/nopasswd"]
source = "files/sudoers.linux"
owner = "root"
group = "root"
mode = "0444"
