[bootstrap.packages]
"apt:dnsutils" = "latest"
"apt:git" = "latest"
"apt:less" = "latest"
"apt:locales" = "latest"
"apt:neovim" = "latest"
"apt:postgresql-client" = "latest"
"apt:rsync" = "latest"
"apt:sqlite3" = "latest"
"apt:sudo" = "latest"
"apt:unzip" = "latest"
"apt:xdg-utils" = "latest"
"apt:zsh" = "latest"
"apt:zsh-autosuggestions" = "latest"
"apt:zsh-syntax-highlighting" = "latest"

[bootstrap.files."/etc/sudoers.d/nopasswd"]
source = "./files/sudoers.linux"
owner = "root"
group = "root"
mode = "0444"

[tasks.post-setup]
depends = ["configure-locales"]

[tasks.configure-locales]
run = "sudo sed -i '/ja_JP.UTF-8/s/^#//' /etc/locale-gen && sudo /usr/sbin/locale-gen --keep-existing"
