[tools]
age = "latest"
deno = "2.3.5"
node = "24.1.0"
ruby = "3.4.4"
slsa-verifier = "latest"
sops = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
verbose_install = true
default_packages_file = "~/.config/mise/default-gems"
ruby_build_opts = "--disable-install-doc"
