[tools]
bat = "0.26.1"
difftastic = "0.69.0"
fzf = "0.74.0"
gh = "2.96.0"
jq = "1.8.2"
op = "2.34.1"
ripgrep = "15.2.0"
ruby = "4.0"
"gem:fasti" = "latest"
"gem:gemoji-cli" = "latest"
"github:sakuro/factorix" = "0.21.0"


[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
minimum_release_age = "3d"

[settings.ruby]
verbose_install = true
default_packages_file = "~/.config/mise/default-gems"
ruby_build_opts = "--disable-install-doc"
