[tools]
deno = "2.0.6"
node = "23.2.0"
ruby = "3.3.6"

[settings]
experimental = true

[settings.ruby]
verbose_install = true
default_packages_file = "~/.config/mise/default-gems"
ruby_build_opts = "--disable-install-doc"
